export default function Head() {
  return (
    <>
      <title>Create Next App</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <meta
        name="theme-color"
        content="#f15025"
        media="(prefers-color-scheme: light)"
      />
      <meta
        name="theme-color"
        content="#872e4e"
        media="(prefers-color-scheme: dark"
      />
      <link rel="icon" href="/favicon.ico" />
      <link rel="stylesheet" href="https://use.typekit.net/gbc3qst.css" />
    </>
  );
}
